import useSWRImmutable from "swr/immutable";

import { generateArray } from "@/utils/misc";
import Head from "next/head";
import { useState } from "react";
import { Tracker } from "@/components/Tracker";
import { Button, Flex, useColorMode } from "@chakra-ui/react";

const fetcher = async (url: string, options: Record<any, any>) => {
  const res = await fetch(url, options);
  const data = await res.json();

  if (res.status !== 200) {
    throw new Error(data.message);
  }
  return data;
};

const mockArray = generateArray(18);

export default function Home() {
  const { data = mockArray } = useSWRImmutable("api/data", fetcher);

  const [reset, setReset] = useState(0);

  const { colorMode, toggleColorMode } = useColorMode();

  const saveExpense = async (
    category: string,
    description: string,
    expense: number
  ) => {
    await fetcher("api/track", {
      method: "POST",
      body: JSON.stringify({
        category: category,
        description: description || "",
        value: expense,
      }),
    });
    setReset((x) => x + 1);
  };

  return (
    <>
      <Head>
        <title>Expense tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Tracker key={reset} data={data} onSave={saveExpense} />
        <Flex as="footer" mt={5} px="10px" py={4}>
          <Button onClick={toggleColorMode} size="sm">
            Toggle Color Mode
          </Button>
        </Flex>
      </main>
    </>
  );
}
